### ISSUE TITLE
Update excel worksheet

### ISSUE THREAD

**Issue by PeterPereira** [ahmedwalid05/FastExcel#23]
Hi,

I'm using the update template code to update some cells, however when I open the file I need to repair it. (Replaced Part: /xl/worksheets/sheet1.xml part with XML error.  Incorrect document syntax. Line 1, column 1013.
)

            FileInfo inputFile = new FileInfo(@"D:\SERVICE\ReportingService\repository\Report_Teste2.xlsx");

            //Create a some rows in a worksheet
            fexcel.Worksheet worksheet = new fexcel.Worksheet();
            List<fexcel.Row> rows = new List<fexcel.Row>();

            for (int rowNumber = 1; rowNumber < 10; rowNumber += 5)
            {
                List<fexcel.Cell> cells = new List<fexcel.Cell>();
                for (int columnNumber = 1; columnNumber < 4; columnNumber += 2)
                {
                    cells.Add(new fexcel.Cell(columnNumber, rowNumber));
                }
                cells.Add(new fexcel.Cell(4, "Updated Row"));

                rows.Add(new fexcel.Row(rowNumber, cells));
            }
            worksheet.Rows = rows;
            

            // Create an instance of Fast Excel
            using (fexcel.FastExcel fastExcel = new fexcel.FastExcel(inputFile))
            {
                // Read the data
                fastExcel.Update(worksheet, "parser_reports_type");
            }

[Report_Teste2.xlsx](https://github.com/mrjono1/FastExcel/files/1460996/Report_Teste2.xlsx)

**Comment by Sibz** [comment]
Have looked into the file you posted, I will need to spend more time testing this.

It appears during output the contents are overwritten and is leaving the following at the end of sheet1.xml:
`ader="0.3" footer="0.3"/></worksheet>`

**Comment by Sibz** [comment]
Is this opening an existing file? If so could I have a copy of the original file?

**Comment by PeterPereira** [comment]
The original file.
[Report_Teste2_original.xlsx](https://github.com/mrjono1/FastExcel/files/1466244/Report_Teste2_original.xlsx)

**Comment by PeterPereira** [comment]
Any luck?

**Comment by ahmedwalid05** [comment]
The Issue was that  if the new `sheet1.xml` was less than the old `sheet1.xml` in length. A portion of the old file was left in the new one.
Fixed in a563c10ab1005b3c4755da993c9c67e237c6df63.
