### ISSUE TITLE
FastExcel.Read(): "An item with the same key has already been added."

### ISSUE THREAD

**Issue by andrewzuku** [ahmedwalid05/FastExcel#24]
Hello,

I'm having the same problem as in the previously closed issue: https://github.com/mrjono1/FastExcel/issues/2

Basically, when I try to read a specific sheet, I get:
> **System.ArgumentException:** 'An item with the same key has already been added.'

**Example Excel Files**
[success.xlsx](https://github.com/mrjono1/FastExcel/files/1537273/success.xlsx)
[error.xlsx](https://github.com/mrjono1/FastExcel/files/1537275/error.xlsx)

**Example code:**
`
var inputFile = new FileInfo("C:\error.xlsx");
using (var fastExcel = new FastExcel.FastExcel(inputFile, true))
{
  var sheet = fastExcel.Read(1);
}
`

Andrew

**Comment by LukasLuMueller** [comment]
https://github.com/LukasLuMueller/fastexcelworkaround/blob/master/FastExcel/SharedStrings.cs

Created a workaround

**Comment by alextorres50** [comment]
same here

**Comment by ArthurAttout** [comment]
Wait, does the actual core method of "Reading" a sheet fails on this library ?

**Comment by bartdk-be** [comment]
Any news on this issue ? Or more info on how to solve ?
Happens on a fairly basic export to a newly created file.

**Comment by LukasMueller187** [comment]
> 
> 
> https://github.com/LukasLuMueller/fastexcelworkaround/blob/bca74093e4fdf26868d9703a16111b8b77865317/FastExcel/SharedStrings.cs#L65
> 
> Created a workaround

Try my modified version.

**Comment by mrjono1** [comment]
Hi I've just updated the readme to say that I am looking for maintainers

**Comment by ahmedwalid05** [comment]
New maintainer here. 
Fixed in ffa8ddb13b0a3ab787bd65a2b4682e739a530590, Thanks @LukasMueller187 for his fix.
