### ISSUE TITLE
Date format?

### ISSUE THREAD

**Issue by DanteNahuel** [ahmedwalid05/FastExcel#33]
When the worksheet is readed, the cells formated as complete Dates return an odd number (43115.47584490741 e.g) and are of String type.
How do I convert these into dates?

**Comment by ivcubr** [comment]
@DanteNahuel What is the format of the cell you are trying to read?

Can you post a sample Excel document and your code that is reading that cell?

**Comment by linkosoft** [comment]
I'm having the same problem


> var worksheet1 = fastExcel.Read(1);
FastExcel.CellRange cellRange = new FastExcel.CellRange("A", "BB");
var cells = worksheet1.GetCellsInRange(cellRange);
var cellValue= cells.FirstOrDefault(x => x.RowNumber == 1 && x.ColumnNumber == 1).Value;
var date = Convert.ToDateTime(cellValue);

**Comment by rozek1szymon** [comment]
same problem

**Comment by rstm-sf** [comment]
This [SO](https://stackoverflow.com/q/11968570) may help you. I think that additional processing should be added to this library.

**Comment by ahmedwalid05** [comment]
Opened a new issue for this #58.
