### ISSUE TITLE
DateTime problem

### ISSUE THREAD

**Issue by yasinsirkecili** [ahmedwalid05/FastExcel#46]
I can't change cell.Value to a datetime object because i don't know a cell's data type c. value always converting a double value therefore i am not sure from it's data type. 

for example;

foreach (var c in r.Cells)   {
      dr[index] = c.Value.ToString();
}

is c.Value a datetime it convert to a double and i don't know the column's data type.

**Comment by ahmedwalid05** [comment]
Duplicate of #43
