### ISSUE TITLE
Example write CellRange

### ISSUE THREAD

**Issue by jhofran** [ahmedwalid05/FastExcel#50]
please if you could support me

try this code and it is not as expected

            Worksheet worksheet = new Worksheet();
            List<Row> rows = new List<Row>();

            //CellRange cellRange = new CellRange("A", "M", 1);

            for (int rowNumber = 1; rowNumber < 6; rowNumber++)
            {
                List<Cell> cells = new List<Cell>();
                cells.Add(new Cell(1, "Demo"));                
                cells.Add(new Cell(13, "Hello" + rowNumber));
                cells.Add(new Cell(14, "Some Text"));
                
                cells[0].Merge(cells[1]);

                rows.Add(new Row(rowNumber, cells));
            }

**Comment by mrjono1** [comment]
@jhofran you haven't explained what you are expecting and what should or shouldn't be happening

**Comment by ahmedwalid05** [comment]
He didn't reply.
