### ISSUE TITLE
How to create a new excel file?

### ISSUE THREAD

**Issue by saklanmazozgur** [ahmedwalid05/FastExcel#65]
Hello,

In the examples of writing to Excel, a ready-made excel file is requested. (templateFile) Is there a way to create a new excel file from scratch? Can you show us an example where we set the file path and name ourselves?

Thank you from now.

**Comment by AkazawaYun** [comment]
> You need a template file. any empty excel file would do.

Thank you for writing this library, but it's a little discommodiousness that we can't create a new xlsx file without "template file" which seems unused...

**Comment by Xriuk** [comment]
> > You need a template file. any empty excel file would do.
> 
> Thank you for writing this library, but it's a little discommodiousness that we can't create a new xlsx file without "template file" which seems unused...

See this: https://github.com/ahmedwalid05/FastExcel/issues/38#issuecomment-485034465

**Comment by WladimirWasilyev** [comment]
I would prefer an ability to create an Excel file without a template.

You could have mentioned in the introduction that it is impossible to use the library without a template...
